version: "3.8"
services:
  steam-monitor:
    image: python:3.11-slim
    container_name: night-feed
    working_dir: /app
    volumes:
      - ./app:/app
      - ./data:/data
    env_file:
      - .env
    command: sh -c "pip install -r /app/requirements.txt && python -u /app/main.py"
    restart: always
